name: massiv-examples

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_ACTOR}/${GITHUB_REF#refs/heads/})"
      id: extract_branch

    - name: Cache
      uses: actions/cache@v2.0.0
      with:
        # A list of files, directories, and wildcard patterns to cache and restore
        path: |
          "~/.stack"
          "massiv-examples/.stack-work"
          "massiv-examples/*/.stack-work"
        # An explicit key for restoring and saving the cache
        key: "${{ steps.extract_branch.outputs.branch }}"
        restore-keys: "*/master"

    - name: Install dependencies
      run: |
        sudo apt-get install freeglut3-dev
        cd massiv-examples
        curl -sSL https://get.haskellstack.org/ | sh -s - -f
        # curl -sSL https://gist.githubusercontent.com/lehins/fd36a8cc8bf853173437b17f6b6426ad/raw/d9ddb32cac2f0dc6800be4fa54d450f0dcda6c60/git-modtime.hs -o git-modtime.hs
        # stack script git-modtime.hs
        stack setup
    - name: Test
      run: |
        stack test --bench --no-run-benchmarks --haddock --no-haddock-deps
